import { z } from 'zod';
import { Random } from '../core/Random';
import { MISSIONS } from '../data/missions';
import { UNIT_DEFS, UNIT_INDEX } from '../data/units';
import type { Mission } from '../missions/Mission';

/**
 * The army of a campaign between its battles: troops that level up, learn skills, change class, wear the
 * equipment bought at the barracks; mercenaries hired at the tavern; the gold of the victories.
 *
 * From The Crusaders (docs/CRUSADERS.md): gold and experience after each mission, more for the optional
 * enemies killed; troops up to level 99; physical skills up to 50 and magic up to 25, Scouting the default
 * skill of the basic troops; promotions and their skill requirements (official guide); random equipment
 * capped at level 30, with experience or SP bonuses on weapons, regenerated by reloading; mercenaries hired
 * with their skills. Every number below (curves, prices, bonuses) is ours: none is documented.
 */

export const SKILLS = ['melee', 'range', 'riding', 'frontal', 'teamwork', 'gunpowder', 'scouting', 'magic'] as const;
export type Skill = (typeof SKILLS)[number];
export const SKILL_NAMES: Record<Skill, string> = {
  melee: 'Mêlée',
  range: 'Tir',
  riding: 'Équitation',
  frontal: 'Frontal',
  teamwork: 'Travail d’équipe',
  gunpowder: 'Poudre',
  scouting: 'Éclaireur',
  magic: 'Magie',
};
export const skillCap = (skill: Skill) => (skill === 'magic' ? 25 : 50);
export const LEVEL_CAP = 99;
export const ITEM_LEVEL_CAP = 30;
/** Troops kept at the barracks (ours). */
export const ARMY_CAP = 8;
const SKILL_POINTS_PER_LEVEL = 3;
const GOLD_PER_KILL = 3;
const XP_PER_KILL = 4;
/** Health stops growing with the level past this one (the original caps it somewhere: ours). */
const HEALTH_LEVEL_CAP = 40;

type Requirements = Partial<Record<Skill, number>>;
interface TroopClass {
  /** Classes it can be promoted from (none: a class you start with or hire). */
  from: string[];
  requires: Requirements;
  /** Soldiers in the troop. */
  count: number;
  /** Skills of a fresh troop of this class. */
  start?: Requirements;
}

/** Classes of Hironeiden. Requirements of the official guide; the spearmen's and the cavalry's are ours. */
export const CLASSES: Record<string, TroopClass> = {
  hir_infantry: { from: [], requires: { melee: 1 }, count: 15, start: { melee: 1, scouting: 1 } },
  hir_heavy_infantry: { from: ['hir_infantry'], requires: { melee: 10 }, count: 15 },
  hir_knight: { from: ['hir_infantry', 'hir_heavy_infantry'], requires: { melee: 15 }, count: 15 },
  hir_spearman: { from: ['hir_infantry'], requires: { melee: 5 }, count: 16, start: { melee: 5, scouting: 1 } },
  hir_archer: { from: [], requires: { melee: 1, range: 3 }, count: 14, start: { melee: 1, range: 3, scouting: 1 } },
  hir_longbowman: { from: ['hir_archer'], requires: { melee: 3, range: 7 }, count: 14 },
  hir_cavalry: { from: [], requires: { melee: 3, riding: 3 }, count: 10, start: { melee: 3, riding: 3 } },
  hir_heavy_cavalry: { from: ['hir_cavalry'], requires: { melee: 7, frontal: 5, riding: 5 }, count: 10 },
  hir_storm_rider: { from: ['hir_cavalry', 'hir_heavy_cavalry'], requires: { melee: 10, riding: 10, frontal: 8 }, count: 6 },
  hir_sapper: { from: [], requires: { melee: 1, teamwork: 1 }, count: 12, start: { melee: 1, teamwork: 1 } },
  hir_mortar: { from: ['hir_sapper'], requires: { melee: 9, gunpowder: 12, teamwork: 8 }, count: 8 },
};

export const className = (type: string) => UNIT_DEFS[UNIT_INDEX.get(type) ?? -1]?.name ?? type;

// ------------------------------------------------------------------ data

const ITEM_KINDS = ['weapon', 'armour', 'accessory'] as const;
export type ItemKind = (typeof ITEM_KINDS)[number];
export const ItemSchema = z.object({
  id: z.string(),
  kind: z.enum(ITEM_KINDS),
  name: z.string(),
  level: z.number().int().min(1).max(ITEM_LEVEL_CAP),
  /** Attack multiplier bonus (0.1 = +10 %). */
  attack: z.number().min(0).default(0),
  /** Flat defence. */
  defense: z.number().min(0).default(0),
  /** Health multiplier bonus. */
  health: z.number().min(0).default(0),
  /** Bonus of experience and of SP earned by the troop. */
  xpBonus: z.number().min(0).default(0),
  spBonus: z.number().min(0).default(0),
  price: z.number().int().positive(),
});
export type Item = z.infer<typeof ItemSchema>;

const SkillsSchema = z.object(Object.fromEntries(SKILLS.map((s) => [s, z.number().int().min(0).default(0)])) as Record<Skill, z.ZodDefault<z.ZodNumber>>);

export const ArmyTroopSchema = z.object({
  id: z.string(),
  name: z.string(),
  /** Unit definition of its soldiers (its class). */
  type: z.string(),
  /** Unit definition of the hero who leads it, if any. */
  hero: z.string().optional(),
  /** Name of the mercenary who leads it, if hired at the tavern. */
  mercenary: z.string().optional(),
  level: z.number().int().min(1).max(LEVEL_CAP),
  xp: z.number().min(0),
  skillPoints: z.number().int().min(0),
  skills: SkillsSchema,
  equipment: z.object({ weapon: ItemSchema.optional(), armour: ItemSchema.optional(), accessory: ItemSchema.optional() }),
});
export type ArmyTroop = z.infer<typeof ArmyTroopSchema>;

export const BattleReportSchema = z.object({
  mission: z.string(),
  gold: z.number().int(),
  goldFromKills: z.number().int(),
  troops: z.array(z.object({ id: z.string(), name: z.string(), kills: z.number().int(), xp: z.number().int(), levels: z.number().int(), level: z.number().int() })),
  recruits: z.array(z.string()),
});
export type BattleReport = z.infer<typeof BattleReportSchema>;

export const CampaignSchema = z.object({
  version: z.literal(1),
  campaign: z.literal('gerald'),
  gold: z.number().int().min(0),
  completed: z.array(z.string()),
  /** Mission to play next; null when the campaign's missions are all done. */
  next: z.string().nullable(),
  troops: z.array(ArmyTroopSchema).min(1),
  inventory: z.array(ItemSchema),
  /** Seed of the armoury's stock and of the tavern; a new one on every load (as in the original). */
  seed: z.number().int(),
  /** Items of the current stock already bought, mercenaries already hired. */
  bought: z.array(z.string()),
  hired: z.array(z.string()),
  /** Troops chosen for the next battle. */
  deployment: z.object({ mission: z.string(), troops: z.array(z.string()) }).nullable(),
  /** The last victory, shown once back at the barracks. */
  report: BattleReportSchema.nullable(),
  serial: z.number().int().min(0),
});
export type CampaignState = z.infer<typeof CampaignSchema>;

export function parseCampaign(raw: unknown): CampaignState {
  return CampaignSchema.parse(raw);
}

// ------------------------------------------------------------------ troops

function freshTroop(state: CampaignState, type: string, name: string, extra: Partial<ArmyTroop> = {}): ArmyTroop {
  const skills = Object.fromEntries(SKILLS.map((s) => [s, CLASSES[type]?.start?.[s] ?? CLASSES[type]?.requires[s] ?? 0])) as Record<Skill, number>;
  return { id: `t${++state.serial}`, name, type, level: 1, xp: 0, skillPoints: 0, skills, equipment: {}, ...extra };
}

/** Gerald's army at the start of his campaign: his guard, archers and spearmen. */
export function newCampaign(seed = Date.now() % 2147483647): CampaignState {
  const state: CampaignState = {
    version: 1,
    campaign: 'gerald',
    gold: 300,
    completed: [],
    next: MISSIONS.find((m) => m.campaign === 'gerald' && m.order === 1)!.id,
    troops: [],
    inventory: [],
    seed,
    bought: [],
    hired: [],
    deployment: null,
    report: null,
    serial: 0,
  };
  state.troops.push(freshTroop(state, 'hir_infantry', 'Garde de Gerald', { hero: 'hero_gerald' }));
  state.troops.push(freshTroop(state, 'hir_archer', 'Archers'));
  state.troops.push(freshTroop(state, 'hir_spearman', 'Lanciers'));
  return state;
}

const clone = (state: CampaignState): CampaignState => structuredClone(state);
const troopOf = (state: CampaignState, id: string) => {
  const t = state.troops.find((x) => x.id === id);
  if (!t) throw new Error(`no troop ${id}`);
  return t;
};

/** Experience from `level` to the next one. */
export const xpToNext = (level: number) => Math.round(80 * level ** 1.4);

function gainXp(troop: ArmyTroop, xp: number): number {
  let levels = 0;
  troop.xp += xp;
  while (troop.level < LEVEL_CAP && troop.xp >= xpToNext(troop.level)) {
    troop.xp -= xpToNext(troop.level);
    troop.level++;
    troop.skillPoints += SKILL_POINTS_PER_LEVEL;
    levels++;
  }
  if (troop.level === LEVEL_CAP) troop.xp = 0;
  return levels;
}

/** Spends a skill point of the troop. */
export function train(state: CampaignState, troopId: string, skill: Skill): CampaignState {
  const s = clone(state);
  const t = troopOf(s, troopId);
  if (t.skillPoints <= 0) throw new Error('no skill point left');
  if (t.skills[skill] >= skillCap(skill)) throw new Error(`${skill} is at its cap`);
  t.skills[skill]++;
  t.skillPoints--;
  return s;
}

const meets = (troop: ArmyTroop, req: Requirements) => Object.entries(req).every(([skill, n]) => troop.skills[skill as Skill] >= (n ?? 0));

/** Classes the troop can change to now, and those it could with more skills (with what they need). */
export function promotions(troop: ArmyTroop): { type: string; ready: boolean; requires: Requirements }[] {
  return Object.entries(CLASSES)
    .filter(([, c]) => c.from.includes(troop.type))
    .map(([type, c]) => ({ type, ready: meets(troop, c.requires), requires: c.requires }));
}

export function promote(state: CampaignState, troopId: string, type: string): CampaignState {
  const s = clone(state);
  const t = troopOf(s, troopId);
  const p = promotions(t).find((x) => x.type === type);
  if (!p?.ready) throw new Error(`${t.name} cannot become ${type}`);
  // A troop named after its class takes the new one's name.
  if (t.name === className(t.type)) t.name = className(type);
  t.type = type;
  return s;
}

/** Sends a troop away (not the hero's). */
export function dismiss(state: CampaignState, troopId: string): CampaignState {
  const s = clone(state);
  const t = troopOf(s, troopId);
  if (t.hero) throw new Error('the hero stays');
  for (const item of Object.values(t.equipment)) if (item) s.inventory.push(item);
  s.troops = s.troops.filter((x) => x.id !== troopId);
  return s;
}

/** What a troop's level, skills and equipment give its men in battle. */
export function troopBoost(troop: ArmyTroop): { health: number; attack: number; defense: number; sp: number } {
  const lv = troop.level - 1;
  const items = Object.values(troop.equipment).filter((i): i is Item => !!i);
  const sum = (key: 'attack' | 'defense' | 'health') => items.reduce((n, i) => n + i[key], 0);
  const ranged = !!UNIT_DEFS[UNIT_INDEX.get(troop.type) ?? -1]?.ranged;
  const skill = ranged ? troop.skills.range : troop.skills.melee;
  return {
    health: 1 + 0.02 * Math.min(lv, HEALTH_LEVEL_CAP) + sum('health'),
    attack: 1 + 0.01 * lv + 0.008 * skill + sum('attack'),
    defense: 0.15 * lv + 0.1 * troop.skills.melee + sum('defense'),
    sp: 1 + items.reduce((n, i) => n + i.spBonus, 0),
  };
}

// ------------------------------------------------------------------ armoury and tavern

const WEAPONS = ['Lames forgées', 'Armes trempées', 'Armes de vétéran', 'Armes de maître', 'Armes de Hironeiden'];
const ARMOURS = ['Cottes de mailles', 'Brigandines', 'Plates d’acier', 'Harnois', 'Harnois de la garde'];
const ACCESSORIES = ['Insignes', 'Étendard', 'Amulettes', 'Reliques', 'Sceau royal'];
const TIERS = [1, 7, 13, 19, 25];
const tierName = (names: string[], level: number) => names[TIERS.filter((t) => level >= t).length - 1];

function rollItem(rng: Random, kind: ItemKind, level: number, id: string): Item {
  const quality = rng.range(0.85, 1.2);
  const item: Item = { id, kind, name: '', level, attack: 0, defense: 0, health: 0, xpBonus: 0, spBonus: 0, price: 1 };
  if (kind === 'weapon') {
    item.attack = round2((0.04 + 0.012 * level) * quality);
    // Some weapons teach faster or fill the SP gauge faster.
    if (rng.chance(0.3)) {
      if (rng.chance(0.5)) item.xpBonus = round2(rng.range(0.1, 0.25));
      else item.spBonus = round2(rng.range(0.1, 0.3));
    }
    item.name = tierName(WEAPONS, level);
  } else if (kind === 'armour') {
    item.defense = round2((1 + 0.35 * level) * quality);
    item.health = round2((0.02 + 0.006 * level) * quality);
    item.name = tierName(ARMOURS, level);
  } else {
    item.health = round2((0.01 + 0.003 * level) * quality);
    if (rng.chance(0.5)) item.xpBonus = round2(rng.range(0.05, 0.15));
    else item.spBonus = round2(rng.range(0.05, 0.2));
    item.name = tierName(ACCESSORIES, level);
  }
  const bonus = 1 + item.xpBonus + item.spBonus;
  item.price = Math.round(((60 + 25 * level ** 1.35) * quality * bonus) / 5) * 5;
  item.name += quality > 1.1 ? ' de qualité' : '';
  return item;
}
const round2 = (x: number) => Math.round(x * 100) / 100;

const topLevel = (state: CampaignState) => Math.max(...state.troops.map((t) => t.level));

/**
 * The armoury's stock: random, regenerated with the seed. Of each kind, one piece the army's least
 * experienced troop can wear, one around its best troop's level.
 */
export function armoury(state: CampaignState): Item[] {
  const rng = new Random(state.seed);
  const top = topLevel(state);
  const low = Math.min(...state.troops.map((t) => t.level));
  const stock: Item[] = [];
  for (const kind of ITEM_KINDS) {
    for (let k = 0; k < 2; k++) {
      const level = Math.min(ITEM_LEVEL_CAP, Math.max(1, k === 0 ? low : top - 1 + rng.int(4)));
      stock.push(rollItem(rng, kind, level, `s${state.seed}-${kind}-${k}`));
    }
  }
  return stock.filter((i) => !state.bought.includes(i.id));
}

export interface Mercenary {
  id: string;
  name: string;
  type: string;
  level: number;
  skills: Record<Skill, number>;
  price: number;
}

const MERCENARY_NAMES = ['Aldric', 'Bertram', 'Cedric', 'Dunstan', 'Edwin', 'Godric', 'Osric', 'Wulfstan', 'Hereward', 'Leofric'];
const HIREABLE = ['hir_infantry', 'hir_archer', 'hir_spearman', 'hir_cavalry', 'hir_sapper'];

/**
 * The tavern's mercenaries, each with his class and skills. Smith comes first (players recall him as the
 * first recruit of Gerald's campaign); the others' names are ours.
 */
export function tavern(state: CampaignState): Mercenary[] {
  const rng = new Random(state.seed ^ 0x5bd1e995);
  const level = Math.max(1, Math.round(state.troops.reduce((n, t) => n + t.level, 0) / state.troops.length));
  const offers: Mercenary[] = [];
  const make = (name: string, type: string): Mercenary => {
    const lv = Math.max(1, level + rng.int(3) - 1);
    const skills = Object.fromEntries(SKILLS.map((s) => [s, CLASSES[type].start?.[s] ?? 0])) as Record<Skill, number>;
    for (let p = 0; p < (lv - 1) * SKILL_POINTS_PER_LEVEL + 2; p++) {
      const useful = Object.keys(CLASSES[type].start ?? {}) as Skill[];
      // Mostly the skills of his class, sometimes another physical one (never magic, the last).
      const skill = rng.chance(0.75) ? useful[rng.int(useful.length)] : SKILLS[rng.int(SKILLS.length - 1)];
      if (skills[skill] < skillCap(skill)) skills[skill]++;
    }
    return { id: `m-${name}`, name, type, level: lv, skills, price: 150 + 60 * lv };
  };
  if (!state.hired.includes('Smith')) offers.push(make('Smith', 'hir_infantry'));
  const names = MERCENARY_NAMES.filter((n) => !state.hired.includes(n));
  while (offers.length < 3 && names.length) {
    const name = names.splice(rng.int(names.length), 1)[0];
    offers.push(make(name, HIREABLE[rng.int(HIREABLE.length)]));
  }
  return offers;
}

export function buy(state: CampaignState, itemId: string): CampaignState {
  const item = armoury(state).find((i) => i.id === itemId);
  if (!item) throw new Error('not in stock');
  if (state.gold < item.price) throw new Error('not enough gold');
  const s = clone(state);
  s.gold -= item.price;
  s.bought.push(item.id);
  s.inventory.push(item);
  return s;
}

export const sellPrice = (item: Item) => Math.floor(item.price / 2);

export function sell(state: CampaignState, itemId: string): CampaignState {
  const s = clone(state);
  const item = s.inventory.find((i) => i.id === itemId);
  if (!item) throw new Error('not in the inventory');
  s.inventory = s.inventory.filter((i) => i !== item);
  s.gold += sellPrice(item);
  return s;
}

/** Puts an item of the inventory on a troop (its level must reach the item's); the old one goes back. */
export function equip(state: CampaignState, troopId: string, itemId: string): CampaignState {
  const s = clone(state);
  const t = troopOf(s, troopId);
  const item = s.inventory.find((i) => i.id === itemId);
  if (!item) throw new Error('not in the inventory');
  if (t.level < item.level) throw new Error(`${t.name} must reach level ${item.level}`);
  s.inventory = s.inventory.filter((i) => i !== item);
  const old = t.equipment[item.kind];
  if (old) s.inventory.push(old);
  t.equipment[item.kind] = item;
  return s;
}

export function unequip(state: CampaignState, troopId: string, kind: ItemKind): CampaignState {
  const s = clone(state);
  const t = troopOf(s, troopId);
  const item = t.equipment[kind];
  if (!item) return s;
  delete t.equipment[kind];
  s.inventory.push(item);
  return s;
}

export function hire(state: CampaignState, mercenaryId: string): CampaignState {
  const m = tavern(state).find((x) => x.id === mercenaryId);
  if (!m) throw new Error('nobody by that name');
  if (state.troops.length >= ARMY_CAP) throw new Error('the barracks are full');
  if (state.gold < m.price) throw new Error('not enough gold');
  const s = clone(state);
  s.gold -= m.price;
  s.hired.push(m.name);
  const troop = freshTroop(s, m.type, `Troupe de ${m.name}`, { mercenary: m.name, level: m.level, skills: { ...m.skills } });
  s.troops.push(troop);
  return s;
}

/** A new stock at the armoury and new faces at the tavern (each load of the save, each victory). */
export function reroll(state: CampaignState, seed: number): CampaignState {
  const s = clone(state);
  s.seed = seed;
  s.bought = [];
  return s;
}

// ------------------------------------------------------------------ battles

export function missionOf(id: string): Mission {
  const m = MISSIONS.find((x) => x.id === id);
  if (!m) throw new Error(`no mission ${id}`);
  return m;
}

/** Chooses the troops of the next battle (the hero's always goes, within the mission's limit). */
export function deploy(state: CampaignState, troopIds: string[], max: number): CampaignState {
  if (!state.next) throw new Error('the campaign is over');
  const s = clone(state);
  const hero = s.troops.find((t) => t.hero)!;
  const ids = [hero.id, ...troopIds.filter((id) => id !== hero.id && s.troops.some((t) => t.id === id))].slice(0, max);
  s.deployment = { mission: state.next, troops: ids };
  return s;
}

/** The deployed troops as the battle needs them: class, soldiers, strength. */
export function deployedTroops(state: CampaignState): { troop: ArmyTroop; count: number; boost: ReturnType<typeof troopBoost> }[] {
  const ids = state.deployment?.troops ?? [];
  return ids.map((id) => troopOf(state, id)).map((troop) => ({ troop, count: CLASSES[troop.type]?.count ?? 15, boost: troopBoost(troop) }));
}

/**
 * After a victory: the mission's gold plus some per enemy killed; its experience shared by the troops that
 * fought, plus some per kill and the bonus of their equipment; recruits join; the next mission opens.
 * Losses are made good between battles (ours: the original's rule is not documented).
 */
export function victory(state: CampaignState, kills: Record<string, number>, seed: number): CampaignState {
  const s = clone(state);
  const mission = missionOf(s.deployment?.mission ?? s.next ?? '');
  const fought = (s.deployment?.troops ?? []).map((id) => troopOf(s, id));
  const totalKills = Object.values(kills).reduce((n, k) => n + k, 0);
  const goldFromKills = totalKills * GOLD_PER_KILL;
  s.gold += mission.reward.gold + goldFromKills;
  const share = Math.round(mission.reward.xp / Math.max(1, fought.length));
  const report: BattleReport = { mission: mission.id, gold: mission.reward.gold + goldFromKills, goldFromKills, troops: [], recruits: [] };
  for (const t of fought) {
    const k = kills[t.id] ?? 0;
    const bonus = 1 + Object.values(t.equipment).reduce((n, i) => n + (i?.xpBonus ?? 0), 0);
    const xp = Math.round((share + k * XP_PER_KILL) * bonus);
    const levels = gainXp(t, xp);
    report.troops.push({ id: t.id, name: t.name, kills: k, xp, levels, level: t.level });
  }
  for (const r of mission.recruits) {
    if (s.troops.length >= ARMY_CAP) break;
    s.troops.push(freshTroop(s, r.type, r.name));
    report.recruits.push(r.name);
  }
  if (!s.completed.includes(mission.id)) s.completed.push(mission.id);
  const next = MISSIONS.find((m) => m.campaign === mission.campaign && m.order === mission.order + 1);
  s.next = next?.id ?? null;
  s.deployment = null;
  s.report = report;
  return reroll(s, seed);
}
