import { describe, expect, it } from 'vitest';
import {
  armoury,
  buy,
  CLASSES,
  deploy,
  deployedTroops,
  dismiss,
  equip,
  hire,
  type CampaignState,
  newCampaign,
  parseCampaign,
  promote,
  promotions,
  reroll,
  sell,
  tavern,
  train,
  troopBoost,
  victory,
  xpToNext,
} from '../../src/campaign/Campaign';
import { MemoryStore } from '../../src/campaign/SaveStore';
import { mission } from '../../src/data/missions';
import { deployMax } from '../../src/missions/Mission';
import { startMission, withArmy } from '../../src/missions/startMission';

const feed = { say: () => {}, cutscene: () => {}, flyover: () => {} };
const guard = (s: CampaignState) => s.troops.find((t) => t.hero)!;

describe('campaign: the army between battles', () => {
  it("starts Gerald's campaign with his guard, archers and spearmen, at Greyhampton", () => {
    const s = newCampaign(7);
    expect(s.next).toBe('greyhampton');
    expect(s.troops.map((t) => [t.name, t.type])).toEqual([
      ['Garde de Gerald', 'hir_infantry'],
      ['Archers', 'hir_archer'],
      ['Lanciers', 'hir_spearman'],
    ]);
    // Scouting, the default skill of basic troops; each class meets its own requirements.
    for (const t of s.troops) {
      expect(t.skills.scouting).toBe(1);
      for (const [skill, n] of Object.entries(CLASSES[t.type].requires)) expect(t.skills[skill as keyof typeof t.skills]).toBeGreaterThanOrEqual(n!);
    }
    // A save survives JSON (IndexedDB stores a structured clone).
    expect(parseCampaign(JSON.parse(JSON.stringify(s)))).toEqual(s);
  });

  it('pays for the victory, shares experience, levels troops up, recruits, opens the next mission', () => {
    let s = deploy(newCampaign(7), [], 3);
    const [g, archers] = s.troops;
    s = deploy(s, [archers.id], 3);
    expect(s.deployment).toEqual({ mission: 'greyhampton', troops: [g.id, archers.id] });
    const gold = s.gold;
    s = victory(s, { [g.id]: 40, [archers.id]: 12 }, 99);
    const reward = mission('greyhampton')!.reward;
    expect(s.gold).toBe(gold + reward.gold + 52 * 3);
    expect(s.next).toBe('ravenmeadow');
    expect(s.completed).toEqual(['greyhampton']);
    expect(s.deployment).toBeNull();
    // The guard killed more: more experience, a level or more, skill points to spend.
    const report = s.report!;
    const rg = report.troops.find((t) => t.id === g.id)!;
    expect(rg.xp).toBeGreaterThan(report.troops.find((t) => t.id === archers.id)!.xp);
    expect(guard(s).level).toBeGreaterThan(1);
    expect(guard(s).skillPoints).toBe(3 * (guard(s).level - 1));
    // The spearmen stayed home: no experience.
    expect(s.troops[2].xp).toBe(0);
    // Ravenmeadow: the archers of the column join.
    s = victory(deploy(s, [], 4), {}, 100);
    expect(s.troops.at(-1)!.name).toBe('Archers de la colonne');
    expect(s.next).toBeNull();
    expect(() => deploy(s, [], 4)).toThrow(/over/);
  });

  it('skills and promotions: an infantry troop with Melee 15 can become knights', () => {
    let s = newCampaign(1);
    const id = guard(s).id;
    s.troops[0].skillPoints = 20;
    expect(promotions(guard(s)).map((p) => [p.type, p.ready])).toEqual([
      ['hir_heavy_infantry', false],
      ['hir_knight', false],
      ['hir_spearman', false],
    ]);
    expect(() => promote(s, id, 'hir_knight')).toThrow();
    for (let i = 0; i < 14; i++) s = train(s, id, 'melee');
    expect(guard(s).skills.melee).toBe(15);
    expect(guard(s).skillPoints).toBe(6);
    expect(promotions(guard(s)).every((p) => p.ready)).toBe(true);
    s = promote(s, id, 'hir_knight');
    expect(guard(s).type).toBe('hir_knight');
    expect(guard(s).hero).toBe('hero_gerald');
    // A troop named after its class takes the new class's name.
    s.troops[1].skillPoints = 6;
    for (let i = 0; i < 4; i++) s = train(s, s.troops[1].id, 'range');
    s = train(train(s, s.troops[1].id, 'melee'), s.troops[1].id, 'melee');
    expect(() => train(s, s.troops[1].id, 'melee')).toThrow(/no skill point/);
    s = promote(s, s.troops[1].id, 'hir_longbowman');
    expect(s.troops[1].name).toBe('Archers longs');
  });

  it('armoury: random stock regenerated by a new seed, gold, item levels, equipment changes the troop', () => {
    let s = newCampaign(3);
    const stock = armoury(s);
    expect(stock).toHaveLength(6);
    expect(armoury(s)).toEqual(stock);
    expect(armoury(reroll(s, 4)).map((i) => i.id)).not.toEqual(stock.map((i) => i.id));
    // Whatever the stock, each kind has a piece for the least experienced troop.
    for (const kind of ['weapon', 'armour', 'accessory']) expect(stock.some((i) => i.kind === kind && i.level === 1)).toBe(true);
    const weapon = stock.find((i) => i.kind === 'weapon')!;
    s.gold = 10_000;
    s = buy(s, weapon.id);
    expect(armoury(s).some((i) => i.id === weapon.id)).toBe(false);
    expect(s.gold).toBe(10_000 - weapon.price);
    const before = troopBoost(guard(s));
    if (weapon.level > 1) {
      expect(() => equip(s, guard(s).id, weapon.id)).toThrow(/level/);
      s.troops[0].level = weapon.level;
    }
    s = equip(s, guard(s).id, weapon.id);
    expect(guard(s).equipment.weapon?.id).toBe(weapon.id);
    expect(troopBoost(guard(s)).attack).toBeGreaterThan(before.attack);
    // Another weapon replaces it; the first goes back to the inventory and can be sold for half.
    const other = armoury(s).find((i) => i.kind === 'weapon')!;
    s = buy(s, other.id);
    s.troops[0].level = Math.max(s.troops[0].level, other.level);
    s = equip(s, guard(s).id, other.id);
    expect(s.inventory.map((i) => i.id)).toEqual([weapon.id]);
    const gold = s.gold;
    s = sell(s, weapon.id);
    expect(s.gold).toBe(gold + Math.floor(weapon.price / 2));
    expect(() => buy({ ...s, gold: 0 }, armoury(s)[0].id)).toThrow(/gold/);
  });

  it('tavern: Smith first, then mercenaries with their class and skills; the barracks have a limit', () => {
    let s = newCampaign(5);
    const offers = tavern(s);
    expect(offers[0].name).toBe('Smith');
    expect(offers).toHaveLength(3);
    s.gold = 5000;
    s = hire(s, offers[0].id);
    const smith = s.troops.at(-1)!;
    expect(smith).toMatchObject({ name: 'Troupe de Smith', mercenary: 'Smith', type: 'hir_infantry', level: offers[0].level });
    expect(tavern(s).some((m) => m.name === 'Smith')).toBe(false);
    s = dismiss(s, smith.id);
    expect(s.troops).toHaveLength(3);
    expect(() => dismiss(s, guard(s).id)).toThrow(/hero/);
  });

  it('saves to a store and reads it back', async () => {
    const store = new MemoryStore();
    expect(await store.load()).toBeNull();
    const s = newCampaign(9);
    await store.save(s);
    expect(await store.load()).toEqual(s);
    await store.clear();
    expect(await store.load()).toBeNull();
  });
});

describe('campaign: the army on the battlefield', () => {
  it('the chosen troops take the places of the mission, veterans are stronger, kills are counted per troop', () => {
    let s = newCampaign(11);
    const m = mission('greyhampton')!;
    expect(deployMax(m)).toBe(3);
    s.troops[0].level = 10;
    s = deploy(s, s.troops.map((t) => t.id), deployMax(m));
    const army = deployedTroops(s).map(({ troop, count, boost }) => ({ id: troop.id, name: troop.name, type: troop.type, hero: !!troop.hero, count, boost }));
    const { mission: deployed, keys } = withArmy(m, army);
    expect(keys.get(s.troops[0].id)).toBe('guard');
    const battle = startMission(deployed, feed);
    const { world, director } = battle;
    const g = director.troopOf.get('guard')!;
    const spears = director.troopOf.get(keys.get(s.troops[2].id)!)!;
    expect(spears.name).toBe('Lanciers');
    expect(director.troopOf.has('archers')).toBe(false);
    // Level 10: more health than the spearmen of level 1 (same base soldier health: 120 and 120).
    const soldier = (t: typeof g) => t.members.find((id) => id !== t.leader && world.c.officer[id] === 0)!;
    expect(world.c.maxHp[soldier(g)]).toBeGreaterThan(world.c.maxHp[soldier(spears)] * 1.1);
    // A kill by a spearman counts for the spearmen.
    world.events.emit('unitDied', { id: 999, team: 1, x: 0, z: 0, killer: spears.members[0] });
    expect(director.kills.get(keys.get(s.troops[2].id)!)).toBe(1);
    // Kills of the enemy's own (or of the player's men) do not count.
    world.events.emit('unitDied', { id: 998, team: 0, x: 0, z: 0, killer: spears.members[0] });
    expect([...director.kills.values()].reduce((a, b) => a + b, 0)).toBe(1);
    expect(xpToNext(1)).toBeGreaterThan(0);
  });
});
